name: LGTM
on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]

jobs:
  lgtm:
    runs-on: ubuntu-latest
    steps:
      - name: LGTM
        uses: Doarakko/test@main
        if: >-
          contains(github.event.comment.body, 'lgtm')
          || contains(github.event.review.body, 'lgtm')
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
